// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u32().primaryKey(),
  gravity: __t.f32(),
  flapForce: __t.f32().name("flap_force"),
  pipeSpeed: __t.f32().name("pipe_speed"),
  pipeIntervalMs: __t.u64().name("pipe_interval_ms"),
  gapSize: __t.f32().name("gap_size"),
  birdStartX: __t.f32().name("bird_start_x"),
});
