// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Bird = __t.object("Bird", {
  playerIdentity: __t.identity(),
  x: __t.f32(),
  y: __t.f32(),
  velocityY: __t.f32(),
  rotation: __t.f32(),
});
export type Bird = __Infer<typeof Bird>;

export const GameConfig = __t.object("GameConfig", {
  id: __t.u32(),
  gravity: __t.f32(),
  flapForce: __t.f32(),
  pipeSpeed: __t.f32(),
  pipeIntervalMs: __t.u64(),
  gapSize: __t.f32(),
  birdStartX: __t.f32(),
});
export type GameConfig = __Infer<typeof GameConfig>;

export const Pipe = __t.object("Pipe", {
  id: __t.u32(),
  x: __t.f32(),
  gapY: __t.f32(),
  speed: __t.f32(),
});
export type Pipe = __Infer<typeof Pipe>;

export const Player = __t.object("Player", {
  identity: __t.identity(),
  username: __t.string(),
  colorHex: __t.string(),
  sessionId: __t.u32(),
  isAlive: __t.bool(),
  score: __t.u32(),
  isReady: __t.bool(),
});
export type Player = __Infer<typeof Player>;

export const Session = __t.object("Session", {
  id: __t.u32(),
  state: __t.string(),
  roundNumber: __t.u32(),
  startedAt: __t.u64(),
});
export type Session = __Infer<typeof Session>;

