// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import FlapReducer from "../flap_reducer";
import JoinGameReducer from "../join_game_reducer";
import RequestStartReducer from "../request_start_reducer";
import SetReadyReducer from "../set_ready_reducer";
import TickReducer from "../tick_reducer";

export type FlapParams = __Infer<typeof FlapReducer>;
export type JoinGameParams = __Infer<typeof JoinGameReducer>;
export type RequestStartParams = __Infer<typeof RequestStartReducer>;
export type SetReadyParams = __Infer<typeof SetReadyReducer>;
export type TickParams = __Infer<typeof TickReducer>;

